import type { NextPage } from "next";
import Head from "next/head";
import styles from "../../../styles/Home.module.css";
import Footer from "../../../components/Footer/footer";
import NavbarComponent from "../../../components/navbar/navbar";


import { attributes, react as LocationsContent } from '../../../content/locations.md';

import LocationsBgHeader from "../../components/locations/sm/locationsSmallHeader/locationsSmallHeader";
import WhereAreWeArticle from "../../components/locations/bg/whereAreWeArticle/whereAreWeArticle";
import AboutLocationArticle from "../../components/locations/bg/aboutLocationArticle/aboutLocationArticle";
import OurBehavioursArticle from "../../components/locations/bg/ourBehavioursArticle/ourBehavioursArticle";
import LocationSliderArticle from "../../components/locations/bg/locationSliderArticle/locationSliderArticle";
import VacanciesArticle from "../../components/locations/bg/vacanciesArticle/vacanciesArticle";
import React from "react";

const HongKongPage: NextPage = () => {

  return (
    <div className={styles.container}>
      <Head>
        <title>Knight Frank Careers</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link
          rel="stylesheet"
          href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css"
          integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3"
        />
        <link
          rel="preload"
          href="/fonts/romain/RomainHeadline-Regular.otf"
          as="font"
          crossOrigin=""
        />
        <link
          rel="preload"
          href="/fonts/suisse/SuisseIntl-Regular.otf"
          as="font"
          crossOrigin=""
        />
      </Head>

      <body>
        <LocationsContent />

        <main className={`${styles.main} ${styles.locationsBigMain}`}>
          <NavbarComponent />
          <div className={styles.grid}>
            <LocationsBgHeader />
            <WhereAreWeArticle />
            <AboutLocationArticle />
            <OurBehavioursArticle />
            <VacanciesArticle />
          </div>
        </main>

        <Footer />
      </body>
    </div>
  );
};

export default HongKongPage;
