backend:
  name: github
  repo: SzczepanIF/wiser-test # Branch to update (optional; defaults to master)
  branch: main
media_folder: public/img
public_folder: img
collections:
  - name: "locations_big"
    label: "Location Big "
    create: true
    folder: 'content/locations/big'
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Country", name: "country", widget: "string" }
      - { label: "Vacancies URL", name: "vacancies_url", widget: "string" }
      - { label: "Where are we", name: "where_are_we", widget: "markdown" }
      - { label: "About Knight Frank", name: "about_knight_frank", widget: "markdown" }
      - label: 'Teams'
        name: "teams"
        widget: list
        fields:
          - { label: "URL", name: 'url', widget: "string" }
  - name: "locations_small"
    label: "Location Small "
    create: true
    folder: 'content/locations/small'
    fields:
          - { label: "Name", name: "name", widget: "string" }
          - { label: "Title", name: "title", widget: "string"}
          - { label: "Country", name: "country", widget: "string"}
          - { label: "Vacancies URL", name: "vacancies_url", widget: "string"}
          - { label: "Where are we", name: "where_are_we", widget: "markdown"}
          - { label: "About Knight Frank", name: "about_knight_frank", widget: "markdown"}
  - name: "pages"
    label: "Pages"
    files:
    - label: "HomePage"
      name: "home"
      file: "content/home.md"
      fields:
        - { label: "Title", name: "title", widget: "string"}
        - { label: "Publish Date", name: "date", widget: "datetime" }
        - { label: "Main Article Title", name: "mainArticleTitle", widget: "string"}
        - { label: "Main Article Description", name: "mainArticleDescription", widget: "markdown"}
        - { label: "Who Are We Article Title", name: "whoAreWeArticleTitle", widget: "string"}
        - { label: "Who Are We Article Description", name: "whoAreWeArticleDescription", widget: "markdown"}
        - { label: "Location Article Title", name: "locationArticleTitle", widget: "string"}
        - { label: "Location Article Description", name: "locationArticleDescription", widget: "markdown"}
        - { label: "Why Knight Frank Article Title", name: "whyKnightFrankArticleTitle", widget: "string"}
        - { label: "Why Knight Frank Article Description", name: "whyKnightFrankArticleDescription", widget: "markdown"}
        - { label: "[Global] Possibilities Article Title (First Line)", name: "possibilitiesArticleTitleLine1", widget: "string"}
        - { label: "[Global] Possibilities Article Title (Second) Line)", name: "possibilitiesArticleTitleLine2", widget: "string"}
        - { label: "[Global] Possibilities Article Description", name: "possibilitiesArticleDescription", widget: "markdown"}
    - label: "Our Business"
      name: "business"
      file: "content/business.md"
      fields:
        - { label: "Title", name: "title", widget: "string"}
        - { label: "Publish Date", name: "date", widget: "datetime" }
        - { label: "Main Article Title", name: "mainArticleTitle", widget: "string"}
        - { label: "Main Article Description", name: "mainArticleDescription", widget: "markdown"}
        - { label: "What Do We Do Article Title", name: "whatDoWeDoArticleTitle", widget: "string"}
        - { label: "What Do We Do Article Description", name: "whatDoWeDoArticleDescription", widget: "markdown"}
        - { label: "Business Area Article Title", name: "businessAreaArticleTitle", widget: "string"}
        - { label: "Business Area Article Description", name: "businessAreaArticleDescription", widget: "markdown"}
    - label: "Why Knight Frank"
      name: "knightfrank"
      file: "content/knightfrank.md"
      fields:
        - { label: "Title", name: "title", widget: "string"}
        - { label: "Publish Date", name: "date", widget: "datetime" }
        - { label: "Main Article Title", name: "mainArticleTitle", widget: "string"}
        - { label: "Main Article Description", name: "mainArticleDescription", widget: "markdown"}
        - { label: "Heart of Knight Frank Article Title", name: "heartOfKnightFrankArticleTitle", widget: "string"}
        - { label: "Heart of Knight Article Description", name: "heartOfKnightFrankArticleDescription", widget: "markdown"}
    - label: "Locations"
      name: "locations"
      file: "content/locations.md"
      fields:
        - { label: "Title", name: "title", widget: "string"}
        - { label: "Publish Date", name: "date", widget: "datetime" }
        - { label: "Body", name: "body", widget: "markdown"}
        - label: 'Asia Pacific - Countries'
          name: "Asia Pacific"
          widget: list
          fields:
            - { label: "Name", name: "name", widget: "string"}
            - { label: "Description", name: "description", widget: "text"}
            - { label: "Type", name: "type", widget: "text"}
        - label: Europe - Countries'
          name: "europe"
          widget: list
          fields:
            - { label: "Name", name: "name", widget: "string"}
            - { label: "Description", name: "description", widget: "text"}
            - { label: "Type", name: "type", widget: "text"}
        - label: Africa & Middle East - Countries'
          name: "africa"
          widget: list
          fields:
            - { label: "Name", name: "name", widget: "string"}
            - { label: "Description", name: "description", widget: "text"}
            - { label: "Type", name: "type", widget: "text"}
        - label: "Early Careers"
          name: "careers"
          file: "content/careers.md"
          fields:
            - { label: "Title", name: "title", widget: "string"}
            - { label: "Publish Date", name: "date", widget: "datetime" }
        - label: "Vacancies"
          name: "vacancies"
          file: "content/vacancies.md"
          fields:
            - { label: "Title", name: "title", widget: "string"}
            - { label: "Publish Date", name: "date", widget: "datetime" }
