import type { NextPage } from "next";
import Head from "next/head";
import styles from "../styles/Home.module.css";
import Footer from "../components/Footer/footer";
import NavbarComponent from "../components/navbar/navbar";
import MainArticle from "./components/business/articles/mainArticle";
import SocialResponsibilityArticle from "./components/business/articles/socialResponsibility";
import WhatDoWeDoArticle from "./components/business/articles/whatDoWeDoArticle";
import BusinessAreasArticle from "./components/business/articles/businessAreasArticle";
import RealisePosibilities from "../components/RealisePossibilities/realisePossibilities";
import GlobalValuesArticle from "./components/business/articles/globalValues";
import MeetUsArticle from "./components/business/articles/meetUs";

import { attributes, react as BusinessContent } from '../content/business.md';

const BusinessPage: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Knight Frank Careers</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link
          rel="stylesheet"
          href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css"
          integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3"
        />
        <link
          rel="preload"
          href="/fonts/romain/RomainHeadline-Regular.otf"
          as="font"
          crossOrigin=""
         />
        <link
          rel="preload"
          href="/fonts/suisse/SuisseIntl-Regular.otf"
          as="font"
          crossOrigin=""
        />
      </Head>

      <body>
        <BusinessContent />
        <main className={styles.main}>
          <NavbarComponent />
          <div className={styles.grid}>
            <MainArticle />
            <WhatDoWeDoArticle />
            <BusinessAreasArticle />
            <SocialResponsibilityArticle />
            <GlobalValuesArticle />
            <MeetUsArticle />
            <RealisePosibilities>
              We’re building the future of property. Seize the opportunity to join us for the journey.
            </RealisePosibilities>
            <br />
            <br />
            <br />
          </div>
          <Footer />
        </main>
      </body>
    </div>
  );
};

export default BusinessPage;
