import type { NextPage } from "next";
import Head from "next/head";
import styles from "../styles/Home.module.css";
import { Subtitle, Title } from "../components/Title";
import Footer from "../components/Footer/footer";
import Article from "../components/Article/article";
import NavbarComponent from "../components/navbar/navbar";
import Button from "../components/Button/button";

const CulturePage: NextPage = () => {
  const articleVariant = "primary";

  return (
    <div className={styles.container}>
      <Head>
        <title>Knight Frank Careers</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link
          rel="stylesheet"
          href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css"
          integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3"
        />
      </Head>

      <body>
        <NavbarComponent />

        <main className={styles.main}>
          <NavbarComponent />
          <div className={styles.grid}>
            <Article variant={articleVariant} className={styles.mainArticle}>
              <Article.TextContainer variant={articleVariant}>
                <Article.Header
                  title="Our culture"
                  titleType={articleVariant}
                  subtitle="Careers at Knight Frank"
                  subtitleEmphasizedText="Knigth Frank"
                />
                <Article.Text>
                  Lorem ipsum dolor sit amet consectetur, adipisicing elit.
                  Dolorem voluptatem aperiam, earum similique quibusdam libero
                  consequuntur dolore laborum fuga cum?
                </Article.Text>
              </Article.TextContainer>
              <Article.Right>
                <div
                  style={{
                    width: 550,
                    height: 550,
                    marginTop: "-170px",
                    marginLeft: "30px",
                    background: 'url("/svg/cultureMain.svg")',
                    backgroundPositionY: "bottom",
                    backgroundPositionX: "right",
                    backgroundRepeat: "no-repeat",
                    backgroundSize: "contain",
                  }}
                />
              </Article.Right>
            </Article>
          </div>
        </main>

        <Footer />
      </body>
    </div>
  );
};

export default CulturePage;
