import type { NextPage } from "next";
import React from "react";
import Head from "next/head";
import styles from "../styles/Home.module.css";
import Image from "next/image";
import Footer from "../components/Footer/footer";
import { Subtitle, Title } from "../components/Title";
import NavbarComponent from "../components/navbar/navbar";
import RealisePosibilities from "../components/RealisePossibilities/realisePossibilities";
import QuoteArticle from "../components/QuoteArticle/quoteArticle";
import { TQuote } from "../utils/types";
import CountUpContainer from "../components/CountUpContainer/countupContainer";
import LocationsArticle from "./components/home/articles/locationsArticle/locationsArticle";
import WhoAreWeArticle from "./components/home/articles/whoAreWeArticle";
import SocialResponsibilityArticle from "./components/business/articles/socialResponsibility";
import MainArticle from "./components/home/articles/mainArticle";
import WhyKnightFrankArticle from "./components/home/articles/whyKnightFrank";

import { attributes, react as HomeContent } from '../content/home.md';

const Home: NextPage = () => {
  const [quotesData, setQuotesData] = React.useState<TQuote[]>([]);

  const countUpData = React.useMemo(
    () => ({
      people: 20000,
      territories: 57,
      globalTeams: 1,
      offices: 488,
    }),
    []
  );

  React.useEffect(() => {
    const getQuotes = async () => {
      const data = await quotesRandomData();
      setQuotesData(data);
    };

    getQuotes();
  }, []);

  return (
    <div className={styles.container}>
      <Head>
        <title>Knight Frank Careers</title>
        <meta name="description" content="Generated by create next app" />
        <link
          rel="stylesheet"
          href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css"
          integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3"
        />
        <link
          rel="preload"
          href="/fonts/romain/RomainHeadline-Regular.otf"
          as="font"
          crossOrigin=""
         />
         <link
          rel="preload"
          href="/fonts/suisse/SuisseIntl-Regular.otf"
          as="font"
          crossOrigin=""
         />
         <link id="favicon" rel="shortcut icon" href="/favicon.ico" type="image/x-icon" />
        <script src="https://identity.netlify.com/v1/netlify-identity-widget.js"></script>

      </Head>
      <body>
      <HomeContent />
      <script src="https://identity.netlify.com/v1/netlify-identity-widget.js"></script>
        <main className={styles.main}>
          <NavbarComponent />
          <div className={styles.grid}>
            <MainArticle />
            <WhoAreWeArticle />
            <div className="mt-5">
              <CountUpContainer data={countUpData} />
            </div>
            <LocationsArticle />
            <WhyKnightFrankArticle />
            <QuoteArticle items={quotesData} />
            <RealisePosibilities>
              We’re building the future of property. Seize the opportunity to join us for the journey.
            </RealisePosibilities>
          </div>
        </main>
        <Footer />
      </body>
    </div>
  );
};

export default Home;

async function quotesRandomData() {
  let data: TQuote[] = [];

  const quotes = [
    "I joined Knight Frank as a project manager in the Design and Delivery Department, and had the opportunity to participate in lots of renovation and development projects right from the start. After two years, I moved departments and joined OSCA – changing roles and gaining cross-functional skills has been so much easier here than I expected. Knight Frank is a very human company, where everyone is really able to express themselves. Right now, I'm feeling professionally fulfilled, and extremely happy – things couldn't be better!",
    "Working for Knight Frank means getting to be part of a global network, and I’ve had frequent opportunities to collaborate with offices in other countries. Every project is a new challenge, and gives me the opportunity to learn new skills, and grow my experience. I am also grateful for all the open-minded and supportive colleagues I’ve had the chance to work with, and who have been a huge part of my wonderful career path.",
    "Opportunity is the name of the game at Knight Frank – working here has opened so many doors that I've never previously thought possible or considered. You have access to an awesome group of professionals around the world and you're encouraged to take charge of your own career.",
  ];

  await fetch("https://randomuser.me/api/?results=3")
    .then((res) => res.json())
    .then(({ results }) => {
      const mapped = (results || []).map((user: any, idx: number) => {
        return {
          quote: quotes[idx],
          author: {
            name: `${user.name.first} ${user.name.last}`,
            avatar: user.picture.medium,
            businessUnit: `${user.id.name || "ACE"}, ${user.login.username}`,
            location: user.location.city,
          },
        };
      });

      data = mapped;
    });

  return data;
}
