import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import { Subtitle, Title } from "../components/Title";
import Footer from "../components/Footer/footer";
import NavbarComponent from "../components/navbar/navbar";
import JobPosition from "../components/JobPosition/jobPosition";
import JobPositionList from "../components/JobPosition/jobPositionList";
import LocationContainer from "../components/Locations/LocationContainer/locationContainer";
import LocationTile from "../components/Locations/LocationTile/locationTile";
import { Article } from "../components/Article";
import RealisePosibilities from "../components/RealisePossibilities/realisePossibilities";

const LocationsPage: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Knight Frank Careers</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link
          rel="stylesheet"
          href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css"
          integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3"
        />
        <link
          rel="preload"
          href="/fonts/romain/RomainHeadline-Regular.otf"
          as="font"
          crossOrigin=""
        />
        <link
          rel="preload"
          href="/fonts/suisse/SuisseIntl-Regular.otf"
          as="font"
          crossOrigin=""
        />
      </Head>

      <body>
        <NavbarComponent />

        <main className={styles.main}>
          <NavbarComponent />
          <div className={styles.grid}>
            <div className="kf-title">
              <Title variant="primary">Locations</Title>
              <Title>Locations Title</Title>
              <Subtitle>Locations Subtitle</Subtitle>
              <img src={"http://via.placeholder.com/640x120"} width="100%" />
            </div>
            <LocationContainer
              data={{
                //   id: 1,
                name: "Europe",
                employeesNumber: 500,
                officesNumber: 23,
                teritorries: [
                  {
                    country: "France",
                    vacancies: 23,
                    URL: "https://www.google.com/",
                  },
                  {
                    country: "Poland",
                    vacancies: 5,
                    URL: "https://www.google.com/",
                  },
                  {
                    country: "Czech Republic",
                    vacancies: 32,
                    URL: "https://www.google.com/",
                  },
                  {
                    country: "United Kingdom",
                    vacancies: 3,
                    URL: "https://www.google.com/",
                  },
                  {
                    country: "Hungary",
                    vacancies: 11,
                    URL: "https://www.google.com/",
                  },
                ],
              }}
            />
            <Article>
              <JobPositionList
                data={[
                  {
                    id: "123-123",
                    title: "Software developer",
                    location: "London",
                    country: "United Kingdon",
                    URL: "/business",
                  },
                  {
                    id: "123-1234",
                    title: "Software developer 2",
                    location: "Warsaw",
                    country: "Poland",
                    URL: "/business",
                  },
                  {
                    id: "1234-1234",
                    title: "Software developer 3",
                    location: "Vancouver",
                    country: "Canada",
                    URL: "/location",
                  },
                ]}
              />
            </Article>
          </div>
          <br /><br />
          <RealisePosibilities>
            Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet
            consectetur, adipisicing elit. Beatae, delectus?
          </RealisePosibilities>
        </main>

        <Footer />
      </body>
    </div>
  );
};

export default LocationsPage;
