import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import { Subtitle, Title } from "../components/Title";
import Footer from "../components/Footer/footer";
import { Article } from "../components/Article/article";
import NavbarComponent from "../components/navbar/navbar";
import HeartOfKnightFrankArticle from "./components/whyknightfrank/articles/heartOfKnightFrankArticle";
import RealisePosibilities from "../components/RealisePossibilities/realisePossibilities";

import { attributes, react as WhyKnightFrankContent } from '../content/knightfrank.md';

const WhyKnightFrankPage : NextPage = () => {

    const articleVariant = 'primary'
  return (
    <div className={styles.container}>
      <Head>
        <title>Knight Frank Careers</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link
          rel="stylesheet"
          href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css"
          integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3"
        />
        <link
          rel="preload"
          href="/fonts/romain/RomainHeadline-Regular.otf"
          as="font"
          crossOrigin=""
         />
         <link
          rel="preload"
          href="/fonts/suisse/SuisseIntl-Regular.otf"
          as="font"
          crossOrigin=""
         />
      </Head>

      <body>
        <WhyKnightFrankContent />
        <NavbarComponent />
        <main className={styles.main}>
          <NavbarComponent />
          <Article variant={articleVariant} className={styles.mainArticle}>
              <Article.TextContainer variant={articleVariant}>
                <Article.Header
                  title="Why Knight Frank"
                  titleType={articleVariant}
                  subtitle="Careers at Knight Frank"
                  subtitleEmphasizedText="Knigth Frank"
                />
                <Article.Text>
                  Lorem ipsum dolor sit amet consectetur, adipisicing elit.
                  Dolorem voluptatem aperiam, earum similique quibusdam libero
                  consequuntur dolore laborum fuga cum?
                </Article.Text>
              </Article.TextContainer>
              <Article.Right>
                <div
                  style={{
                    width: 550,
                    height: 550,
                    marginTop: "-170px",
                    marginLeft: "30px",
                    background: 'url("/svg/whyKnightFrankMain.svg")',
                    backgroundPositionY: "bottom",
                    backgroundPositionX: "right",
                    backgroundRepeat: "no-repeat",
                    backgroundSize: "contain",
                  }}
                />
              </Article.Right>
            </Article>
            <HeartOfKnightFrankArticle />
            <br/><br/>
            <RealisePosibilities>
              Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet
              consectetur, adipisicing elit. Beatae, delectus?
            </RealisePosibilities>
        </main>

        <Footer />
      </body>
    </div>
  );
};

export default WhyKnightFrankPage;
